jobs:
  test-on-mac:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - continue-on-error: true
      name: Setup Java Version
      uses: actions/setup-java@v2
      with:
        cache: gradle
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Run Cases
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 22
        arch: x86_64
        profile: Nexus 6
        script: './gradlew connectedCheck

          ./gradlew build

          ./gradlew :library:createDebugAndroidTestCoverageReport --info --stacktrace

          ./gradlew connectedAndroidTest  --info --stacktrace

          '
    - continue-on-error: true
      name: Upload coverage.txt
      run: 'bash <(curl -s https://codecov.io/bash)

        '
name: Run Test Cases
on:
  repository_dispatch:
    types: trigger-ga___ci-test.yml
